### ISSUE TITLE
Enable GPU computation with numba

### ISSUE THREAD

**Issue by esarradj** [acoular/acoular#140]
Some calculations with Numba can easily be done on a GPU without much implementation effort. 
The `@guvectorize` decorator has a target option that can be set to cuda. One could at a new attribute `config.cuda=False` to the Config class that is either False or True corresponding to the target option to either `parallel` or `cuda`.

**Comment by adku1173** [comment]
Unfortunately, it's not as simple as I thought. Using the `'cuda'` argument in the `@guvectorize` decorator results in the following error message for all steering vector formulations: 

```
Traceback (most recent call last):
  File "/workspace/cuda_test.py", line 2, in <module>
    from acoular import __file__ as bpath, MicGeom, WNoiseGenerator, PointSource,\
  File "/usr/local/lib/python3.8/site-packages/acoular-20.10-py3.8.egg/acoular/__init__.py", line 74, in <module>
    from .tbeamform import IntegratorSectorTime, \
  File "/usr/local/lib/python3.8/site-packages/acoular-20.10-py3.8.egg/acoular/tbeamform.py", line 38, in <module>
    from .fbeamform import SteeringVector, L_p
  File "/usr/local/lib/python3.8/site-packages/acoular-20.10-py3.8.egg/acoular/fbeamform.py", line 55, in <module>
    from .fastFuncs import beamformerFreq, calcTransfer, calcPointSpreadFunction, \
  File "/usr/local/lib/python3.8/site-packages/acoular-20.10-py3.8.egg/acoular/fastFuncs.py", line 206, in <module>
    def _freqBeamformer_Formulation1AkaClassic_FullCSM(csm, distGridToArrayCenter, distGridToAllMics, waveNumber, signalLossNormalization, result, normalizeSteer):
  File "/usr/local/src/acoular/.eggs/numba-0.51.2-py3.8-linux-x86_64.egg/numba/np/ufunc/decorators.py", line 177, in wrap
    guvec = GUVectorize(func, signature, **kws)
  File "/usr/local/src/acoular/.eggs/numba-0.51.2-py3.8-linux-x86_64.egg/numba/np/ufunc/decorators.py", line 49, in __new__
    return imp(func, signature, identity=identity, cache=cache,
  File "/usr/local/src/acoular/.eggs/numba-0.51.2-py3.8-linux-x86_64.egg/numba/np/ufunc/deviceufunc.py", line 449, in __init__
    assert len(self.outputsig) == 1, "only support 1 output"
AssertionError: only support 1 output

```

The error is due to the signature `'(m,m),(),(m),(),()->(),()'` in fastFuncs.py . Numbas CUDA implementation does not allow to have more than one output here.

**Comment by artpelling** [comment]
There has been some recent developments https://numba.readthedocs.io/en/latest/cuda/overview.html#cuda-deprecation-status

This might be worth revisiting now
