### ISSUE TITLE
acoular installation fails because PyTables does not support NumPy 2.0 

### ISSUE THREAD

**Issue by artpelling** [acoular/acoular#278]
### Version Dependencies

Acoular installation fails for all Python versions above 3.8.
3.8 uses `numpy-1.24.4` and `tables-3.4.4`.
This also affects all CI currently.
### Bug Description

I think the error has something to do with the [new type promotion](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion) in Numpy 2.0.
Looks like PyTables is working on [Numpy 2.0 support](https://github.com/PyTables/PyTables/pull/1160) with the next release.

@acoular/acoular-development-team We could look into this and maybe do something about the type promotion ourselves. Otherwise, we would need to exclude Numpy 2.0 from the dependencies for now.

### Error message:

```shell
cmd [1] | python -c "import acoular"
/home/runner/.local/share/hatch/env/virtual/acoular/Hq4jV1Jp/tests.py3.9/lib/python3.9/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)
/home/runner/work/acoular/acoular/acoular/h5files.py:5: UserWarning: We detected that Numpy is already loaded and uses OpenBLAS. Because this conflicts with Numba parallel execution, we disable parallel execution for now and processing might be slower. To speed up, either import Numpy after Acoular or set environment variable OPENBLAS_NUM_THREADS=1 before start of the program.
  from .configuration import config
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/acoular/acoular/acoular/__init__.py", line 9, in <module>
    from . import demo, tools
  File "/home/runner/work/acoular/acoular/acoular/tools/__init__.py", line 14, in <module>
    from .aiaa import (
  File "/home/runner/work/acoular/acoular/acoular/tools/aiaa.py", line 40, in <module>
    from acoular.h5files import H5FileBase, _get_h5file_class
  File "/home/runner/work/acoular/acoular/acoular/h5files.py", line 46, in <module>
    import tables
  File "/home/runner/.local/share/hatch/env/virtual/acoular/Hq4jV1Jp/tests.py3.9/lib/python3.9/site-packages/tables/__init__.py", line 44, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
  File "tables/utilsextension.pyx", line 1, in init tables.utilsextension
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
```


### Issue Severity

None

**Comment by artpelling** [comment]
I just realized that this affects all new `acoular` installations currently.
